// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: execution.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Kernel.SmartContractExecution {

  /// <summary>Holder for reflection information generated from execution.proto</summary>
  public static partial class ExecutionReflection {

    #region Descriptor
    /// <summary>File descriptor for execution.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExecutionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9leGVjdXRpb24ucHJvdG8SBGFlbGYiYgoaRXhlY3V0aW9uT2JzZXJ2ZXJU",
            "aHJlc2hvbGQSIAoYZXhlY3V0aW9uX2NhbGxfdGhyZXNob2xkGAEgASgFEiIK",
            "GmV4ZWN1dGlvbl9icmFuY2hfdGhyZXNob2xkGAIgASgFQiWqAiJBRWxmLktl",
            "cm5lbC5TbWFydENvbnRyYWN0RXhlY3V0aW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Kernel.SmartContractExecution.ExecutionObserverThreshold), global::AElf.Kernel.SmartContractExecution.ExecutionObserverThreshold.Parser, new[]{ "ExecutionCallThreshold", "ExecutionBranchThreshold" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ExecutionObserverThreshold : pb::IMessage<ExecutionObserverThreshold>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExecutionObserverThreshold> _parser = new pb::MessageParser<ExecutionObserverThreshold>(() => new ExecutionObserverThreshold());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExecutionObserverThreshold> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Kernel.SmartContractExecution.ExecutionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecutionObserverThreshold() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecutionObserverThreshold(ExecutionObserverThreshold other) : this() {
      executionCallThreshold_ = other.executionCallThreshold_;
      executionBranchThreshold_ = other.executionBranchThreshold_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExecutionObserverThreshold Clone() {
      return new ExecutionObserverThreshold(this);
    }

    /// <summary>Field number for the "execution_call_threshold" field.</summary>
    public const int ExecutionCallThresholdFieldNumber = 1;
    private int executionCallThreshold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ExecutionCallThreshold {
      get { return executionCallThreshold_; }
      set {
        executionCallThreshold_ = value;
      }
    }

    /// <summary>Field number for the "execution_branch_threshold" field.</summary>
    public const int ExecutionBranchThresholdFieldNumber = 2;
    private int executionBranchThreshold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ExecutionBranchThreshold {
      get { return executionBranchThreshold_; }
      set {
        executionBranchThreshold_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExecutionObserverThreshold);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExecutionObserverThreshold other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExecutionCallThreshold != other.ExecutionCallThreshold) return false;
      if (ExecutionBranchThreshold != other.ExecutionBranchThreshold) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ExecutionCallThreshold != 0) hash ^= ExecutionCallThreshold.GetHashCode();
      if (ExecutionBranchThreshold != 0) hash ^= ExecutionBranchThreshold.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ExecutionCallThreshold != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ExecutionCallThreshold);
      }
      if (ExecutionBranchThreshold != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ExecutionBranchThreshold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ExecutionCallThreshold != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ExecutionCallThreshold);
      }
      if (ExecutionBranchThreshold != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ExecutionBranchThreshold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ExecutionCallThreshold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExecutionCallThreshold);
      }
      if (ExecutionBranchThreshold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExecutionBranchThreshold);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExecutionObserverThreshold other) {
      if (other == null) {
        return;
      }
      if (other.ExecutionCallThreshold != 0) {
        ExecutionCallThreshold = other.ExecutionCallThreshold;
      }
      if (other.ExecutionBranchThreshold != 0) {
        ExecutionBranchThreshold = other.ExecutionBranchThreshold;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ExecutionCallThreshold = input.ReadInt32();
            break;
          }
          case 16: {
            ExecutionBranchThreshold = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ExecutionCallThreshold = input.ReadInt32();
            break;
          }
          case 16: {
            ExecutionBranchThreshold = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
